.\" Manpage for git-bug.
.\" Contact Vanya or Max to correct errors or typos.
.TH man 7 "03 November 2016" "1.0" "git-bug man page"
.SH NAME
git bug \- Bugs your git:)
.SH SYNOPSIS
git bug
.SH DESCRIPTION
git bug is high level shell program which does nothing. 
.SH OPTIONS
The git bug does not take any options. However, you can supply us.
.SH SEE ALSO
Psychosis, Something Made Them Do It, Survival Training, Self-Medication, Adorable Baby Elves
.SH BUGS
It's own existance is a bug!
.SH AUTHOR
XORED Core
