#!/bin/sh
FILE=".viin"
REF="refs/ISSUES"

if [ "$1" = "-m" ]
then
	echo $2 > $FILE
else
	"${EDITOR:-vi}" $FILE
fi

if [ -s $FILE ]
then

	if [ -f ./.git/index ]
	then
		mv ./.git/index ./.git/index2
	fi

	STATUS=`echo open | git hash-object -w --stdin`
	LINE=`head -1 $FILE`
	SUMMARY=`echo $LINE | git hash-object -w --stdin`
	DESCRIPTION=`sed -i 1d $FILE | git hash-object -w $FILE`

	git update-index --add --cacheinfo 100644 $STATUS status
	git update-index --add --cacheinfo 100644 $SUMMARY summary
	git update-index --add --cacheinfo 100644 $DESCRIPTION description
	TREE=`git write-tree`
	git rm status >> /dev/null
	git rm summary >> /dev/null
	git rm description >> /dev/null

	ISSUE=`echo issue | git commit-tree $TREE`
	echo $ISSUE

	BLOB=`echo $ISSUE | git hash-object -w --stdin`
	git update-index --add --cacheinfo 120000 $BLOB $ISSUE
	TREE=`git write-tree`
	git rm $ISSUE >> /dev/null

	if git show-ref --quiet --verify $REF;
	then 
		ISSUE=`echo issues | git commit-tree $TREE -p $REF`
	else
		ISSUE=`echo issues | git commit-tree $TREE`
	fi

	git update-ref $REF $ISSUE

	rm ./.git/index

	if [ -f ./.git/index2 ]
	then
		mv ./.git/index2 ./.git/index
	fi

fi

if [ -f $FILE ]
then
	rm $FILE
fi
