#!/bin/bash

git_bug_resolve()
{
	REF="refs/heads/ISSUES"

#ищем путь до репозитория и проверяем на его наличие
	local GIT_DIR="$(git rev-parse --show-toplevel)"/.git
	if [ ! -d "$GIT_DIR" ]
	then
		exit 1
	fi

#проверяем наличие аргументов
	if [ "$#" -eq 0 ]
	then
		echo "Error: Not specified hash of issue"
		exit 1
	fi

#проверка существует ли хотя бы одно issue
	if ! git show-ref --quiet --verify "$REF"
	then
		echo "Error: Not created any issue"
		exit 1
	fi

#ищем хэш того чего указан короткий хэш
	local NAME_OF_ISSUE="$(git log --pretty="%H" $1 2>/dev/null)"
	if [ "$NAME_OF_ISSUE" = "" ]
	then
		echo "Error: Issue not found"
		exit 1
	fi

#вычисляем хэш issue, проверяем его на существование
#здесь и далее HASH это хеш блоба, который хранит хэш issue
	local HASH=$(git ls-tree "$REF" "$NAME_OF_ISSUE")
	if [ "$HASH" = "" ]
	then
		echo "Error: Issue not found"
		exit 1
	fi
	local HASH_OF_ISSUE="$(git cat-file -p "$(echo "$HASH" | awk '{print $3}' )")"	

	local STATUS="$(git cat-file -p "$(echo `git ls-tree "$HASH_OF_ISSUE" status` | awk '{print $3}' )")"
	if [ "$STATUS" = "resolved" ]
	then
		echo "Issue already resolved"
		exit 1
	fi

#прячем индекс, чтобы замести следы
	[ -f "$GIT_DIR/index" ] && mv -f "$GIT_DIR/index" "$GIT_DIR/index$$"

	git read-tree "$HASH_OF_ISSUE"^{tree}
	git rm status >/dev/null 2>&1

	local HASH_OF_STATUS=$(echo resolved | git hash-object -w --stdin)
	git update-index --add --cacheinfo 100644 $HASH_OF_STATUS status
	local TREE=$(git write-tree)
	git rm status >/dev/null 2>&1
	git rm summary >/dev/null 2>&1
	git rm description >/dev/null 2>&1

	local HASH_OF_ISSUE=$(echo issue | git commit-tree $TREE -p $HASH_OF_ISSUE)
	local HASH=$(echo $HASH_OF_ISSUE | git hash-object -w --stdin)

	git read-tree "$REF"^{tree}
	git rm "$NAME_OF_ISSUE" >/dev/null 2>&1
	git update-index --add --cacheinfo 120000 $HASH "$NAME_OF_ISSUE"
	local TREE=$(git write-tree)
	HASH_OF_ISSUES=$(echo issues | git commit-tree $TREE -p "$REF")
	git update-ref "$REF" $HASH_OF_ISSUES

#чистим индекс и возвращаем спрятанный
	rm -f "$GIT_DIR/index"
	[ -f "$GIT_DIR/index$$" ] && mv -f "$GIT_DIR/index$$" "$GIT_DIR/index"
}

git_bug_resolve "$@"
