#!/usr/bin/env sh

TREE_HASH=

detect_hash_error()
{
	if [ -z "$1" ]
	then
		echo "This hash ($2) is not found."
		exit 1
	fi
}

get_tree_hash() 
{
	BUF=$(git cat-file -p "$1") 2>/dev/null
	detect_hash_error "$BUF" "$1"

	set $BUF

	TREE_HASH=$(echo "$2")
}

git_bug_hash()
{
	if [ "$#" -eq "0" ]
	then
		echo "Please enter the correct data."
		exit 1
	fi

	HASH="$1"
	get_tree_hash "$HASH"

	BUF=$(git cat-file -p $TREE_HASH) 2>/dev/null
	detect_hash_error "$BUF" "$TREE_HASH"

	set $BUF

	while [ "$#" -ne "0" ]
	do
		case "$4" in
			"description") 
				DESCRIPTION_HASH="$3"
				;;
			"summary")
				SUMMARY_HASH="$3"
				;;
			"status")
				STATUS_HASH="$3"
				;;
		esac

		shift 4
	done

	echo "Issue: $HASH"

	STATUS=$(git cat-file -p $STATUS_HASH)
	echo "Status: $STATUS"

	SUMMARY=$(git cat-file -p $SUMMARY_HASH)
	echo "Summary: $SUMMARY"
		
	DESCRIPTION=$(git cat-file -p $DESCRIPTION_HASH)
	echo "Description:\n$DESCRIPTION"
}

git_bug_hash "$@"
